version: '3.8'
services:
  #mongodb database
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    # Version 0.54.0 because latest doesn't show server status, change when fixed.
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongodb
  #postgresql database
  postgres:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=studrivedatabase
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@studrive.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  #user-service
  user-service:
    build: ./user-service
    ports:
      - "9001:8080"
  #offer-service
  offer-service:
    build: ./offer-service
    ports:
      - "9002:8080"

volumes:
  mongodbdata: {}
  postgresdata: {}

networks:
  mongo:
    name: mongodb-network
  postgres:
    name: postgres-network