version: '3.8'
services:
  #mongodb database
  mongodb:
    # Version 4.4 because latest doesn't run on Ubuntu Host Server
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    # Version 0.54.0 because latest doesn't show server status, change when fixed.
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongodb
  #postgresql database
  postgres:
    image: postgres
    container_name: postgresdb
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=studrivedatabase
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@studrive.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
  #rabbitmq
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
  #studrive-gateway
  studrive-gateway:
    build: ./studrive-gateway
    ports:
      - "9000:8080"
    environment:
      - USERSERVICE_URL=http://user-service:8080
      - OFFERSERVICE_URL=http://offer-service:8080
      - ORDERSERVICE_URL=http://order-service:8080
    volumes:
      - httpTrace:/data/csv
  #user-service
  user-service:
    build: ./user-service
    ports:
      - "9001:8080"
    depends_on:
      - postgres
    volumes:
      - httpTrace:/data/csv
  #offer-service
  offer-service:
    build: ./offer-service
    ports:
      - "9002:8080"
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - httpTrace:/data/csv
  #order-service
  order-service:
    build: ./order-service
    ports:
      - "9003:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - USERSERVICE_URL=http://user-service:8080
      - OFFERSERVICE_URL=http://offer-service:8080
    volumes:
      - httpTrace:/data/csv
  #accounting-service
  accounting-service:
    build: ./accounting-service
    ports:
      - "9004:8080"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  mongodbdata: { }
  postgresdata: { }
  httpTrace: { }