# This file is for defining api-gateway routes only. For other properties use application.properties file
# in same folder.
# Outsource this in a config server in a later stage of the project.
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Microservices architecture paths
        - id: user-route
          uri: http://user-service:8080
          predicates:
            Path=/v1/users/**
        - id: offer-route
          uri: http://offer-service:8080
          predicates:
            Path=/v1/rides/**
        - id: order-route
          uri: http:order-service:8080
          predicates:
            Path=/v1/seats/**

        # Swagger-ui paths
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs
        - id: offer-service
          uri: http://offer-service:8080
          predicates:
            - Path=/offer/v3/api-docs
          filters:
            - RewritePath=/offer/v3/api-docs, /v3/api-docs
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/order/v3/api-docs
          filters:
            - RewritePath=/order/v3/api-docs, /v3/api-docs
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: userOpenapi
          uri: http://localhost:8080
          predicates:
            - Path=/user/v1/**
          filters:
            - RewritePath=/user/v1/(?<path>.*), /v1/$\{path}
        - id: offerOpenapi
          uri: http://localhost:8080
          predicates:
            - Path=/offer/v1/**
          filters:
            - RewritePath=/offer/v1/(?<path>.*), /v1/$\{path}
        - id: orderOpenapi
          uri: http://localhost:8080
          predicates:
            - Path=/order/v1/**
          filters:
            - RewritePath=/order/v1/(?<path>.*), /v1/$\{path}

springdoc:
  swagger-ui:
    path: /studrive-swagger
    use-root-path: true
    disable-swagger-default-url: true
    display-request-duration: true
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: offer
        url: /v3/api-docs/offer
      - name: order
        url: /v3/api-docs/order