# This file is for defining api-gateway routes only. For other properties use application.properties file
# in same folder.
# Outsource this in a config server in a later stage of the project.

urls:
    user-service: ${USERSERVICE_URL:http://localhost:9001}
    offer-service: ${OFFERSERVICE_URL:http://localhost:9002}
    order-service: ${ORDERSERVICE_URL:http://localhost:9003}
    localhost: http://localhost:${server.port}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Microservices routes
        - id: user-route
          uri: ${urls.user-service}
          predicates:
            Path=/v1/users/**
          filters:
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: user-circuit
                fallbackUri: forward:/circuit-fallback
        - id: offer-route
          uri: ${urls.offer-service}
          predicates:
            Path=/v1/rides/**
          filters:
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: offer-circuit
                fallbackUri: forward:/circuit-fallback
        - id: order-route
          uri: ${urls.order-service}
          predicates:
            Path=/v1/seats/**
          filters:
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: order-circuit
                fallbackUri: forward:/circuit-fallback

          # Swagger-ui routes
        - id: user-service
          uri: ${urls.user-service}
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs
        - id: offer-service
          uri: ${urls.offer-service}
          predicates:
            - Path=/offer/v3/api-docs
          filters:
            - RewritePath=/offer/v3/api-docs, /v3/api-docs
        - id: order-service
          uri: ${urls.order-service}
          predicates:
            - Path=/order/v3/api-docs
          filters:
            - RewritePath=/order/v3/api-docs, /v3/api-docs
        - id: openapi
          uri: ${urls.localhost}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: userOpenapi
          uri: ${urls.localhost}
          predicates:
            - Path=/user/v1/**
          filters:
            - RewritePath=/user/v1/(?<path>.*), /v1/$\{path}
        - id: offerOpenapi
          uri: ${urls.localhost}
          predicates:
            - Path=/offer/v1/**
          filters:
            - RewritePath=/offer/v1/(?<path>.*), /v1/$\{path}
        - id: orderOpenapi
          uri: ${urls.localhost}
          predicates:
            - Path=/order/v1/**
          filters:
            - RewritePath=/order/v1/(?<path>.*), /v1/$\{path}

# Swagger-ui config
springdoc:
  swagger-ui:
    path: /studrive-swagger
    use-root-path: true
    disable-swagger-default-url: true
    display-request-duration: true
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: offer
        url: /v3/api-docs/offer
      - name: order
        url: /v3/api-docs/order

# CircuitBreaker config
resilience4j:
  circuitbreaker:
    instances:
      user-circuit:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true
      offer-circuit:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true
      order-circuit:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true
  timelimiter:
    instances:
      user-circuit:
        timeoutDuration: 2s
      offer-circuit:
        timeoutDuration: 2s
      order-circuit:
        timeoutDuration: 2s
