CREATE SCHEMA IF NOT EXISTS userservice;

CREATE TABLE IF NOT EXISTS userservice.users (
    ID SERIAL PRIMARY KEY,
    MATRICULATIONNR VARCHAR(20) NOT NULL,
    UNIVERSITY VARCHAR(150) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    PAYMENTDETAILID BIGINT,
    UNIQUE(EMAIL)
);

CREATE TABLE IF NOT EXISTS userservice.paymentDetails (
    ID SERIAL PRIMARY KEY,
    COUNTRYCODE VARCHAR(2) NOT NULL,
    CHECKDIGIT INTEGER NOT NULL,
    BANKCODE INTEGER NOT NULL,
    ACCOUNTNUMBER INTEGER NOT NULL
);